#!/usr/bin/env python3
# Generate an assembly export table from a list of symbol names (one per line).
# Produces {name-string, &symbol} pairs the loader's resolver scans. Using asm
# lets us take the address of mangled C++ symbols by their raw linker name,
# which C++ source cannot do portably. The eboot link resolves each &symbol
# against its own definitions; a name the eboot lacks becomes an undefined-
# symbol link error - a built-in check that every needed symbol is present.
import sys
names = [l.strip() for l in sys.stdin if l.strip() and not l.startswith('#')]
names = sorted(set(names))
out = []
out.append('// generated by gen_exports.py - do not edit')
out.append('    .section .rodata')
for i, n in enumerate(names):
    # emit the name string
    out.append(f'.Lname{i}: .asciz "{n}"')
out.append('    .section .data')
out.append('    .globl g_host_exports')
out.append('    .globl g_host_exports_count')
out.append('    .p2align 3')
out.append('g_host_exports:')
for i, n in enumerate(names):
    out.append(f'    .quad .Lname{i}')
    out.append(f'    .quad {n}')          # address of the symbol, resolved at link
out.append('    .quad 0')
out.append('    .quad 0')
out.append('g_host_exports_count:')
out.append(f'    .quad {len(names)}')
sys.stdout.write('\n'.join(out) + '\n')
