#!/usr/bin/env python3
# Generate a C export table from a list of symbol names (one per line): the
# {name, address} pairs the binary-add-on loader's resolver scans to bind an
# add-on's C/C++ runtime imports to the eboot's own copies.
#
# Why C with a startup constructor, not an assembly table of `.quad symbol`:
# a static array of absolute symbol addresses needs one R_X86_64_RELATIVE (or
# _64) relocation per entry in .data. A large run of those made the FSELF
# converter segfault. Instead the table's address slots start empty and a
# __attribute__((constructor)) fills them at startup via `&symbol`, which the
# compiler emits as RIP-relative `lea` - no static data relocation at all, the
# same shape as the rest of the eboot. The link still fails on a missing
# symbol (each is declared extern and its address taken), keeping the built-in
# "every needed symbol is present" check.
#
# C++ names are mangled; their mangled form is a valid C identifier only via an
# asm label, so each symbol is declared `extern char NAME_i[] asm("<mangled>")`.
import sys

names = [l.strip() for l in sys.stdin if l.strip() and not l.startswith('#')]
names = sorted(set(names))

out = []
out.append('/* generated by ps5-gen-addon-exports.py - do not edit */')
out.append('#include <stddef.h>')
out.append('struct HE { const char* name; void* addr; };')
out.append('')
# declare each symbol with an asm() label so mangled C++ names are legal here
for i, n in enumerate(names):
    out.append(f'extern char sym_{i}[] __asm__("{n}");')
out.append('')
# the name strings (const -> .rodata, no relocations)
for i, n in enumerate(names):
    esc = n.replace('\\', '\\\\').replace('"', '\\"')
    out.append(f'static const char name_{i}[] = "{esc}";')
out.append('')
# strong definitions overriding HostExports.cpp's weak-empty defaults
out.append(f'struct HE g_host_exports[{len(names) + 1}];')
out.append(f'unsigned long g_host_exports_count = {len(names)};')
out.append('')
out.append('__attribute__((constructor))')
out.append('static void ps5_fill_host_exports(void)')
out.append('{')
for i in range(len(names)):
    out.append(f'  g_host_exports[{i}].name = name_{i};')
    out.append(f'  g_host_exports[{i}].addr = (void*)sym_{i};')
out.append(f'  g_host_exports[{len(names)}].name = 0;')
out.append(f'  g_host_exports[{len(names)}].addr = 0;')
out.append('}')
sys.stdout.write('\n'.join(out) + '\n')
