#!/usr/bin/env bash
# Stage 2: build the test binary add-on, generate the export table from its
# imports, and stage it into the title so the next deploy bundles it. Proves
# on the console that Kodi's binary-add-on path works through ps5elf.
#
# After running this and re-deploying, enable the add-on in Kodi (Add-ons ->
# My add-ons -> Services -> PS5 Binary Loader Test) and watch klog for the
# "[test.binary.ps5] STAGE 2 PASS" line.
set -uo pipefail
export PS5_PAYLOAD_SDK="${PS5_PAYLOAD_SDK:-/opt/ps5-payload-sdk}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLANGXX="$PS5_PAYLOAD_SDK/bin/prospero-clang++"
ADDON="$HERE/addons/test.binary.ps5"
ELFDIR="$HERE/overlay/xbmc/platform/ps5/elf"
[ -x "$CLANGXX" ] || { echo "!! $CLANGXX not found"; exit 1; }

echo "==> building test_binary_ps5.so"
"$CLANGXX" -shared -fPIC -fexceptions -frtti -O2 -std=c++17 \
  -o "$ADDON/test_binary_ps5.so" "$ADDON/test_binary_ps5.cpp" || exit 1

echo "==> its undefined symbols (the export table the eboot must provide):"
NM="$PS5_PAYLOAD_SDK/bin/llvm-nm"; [ -x "$NM" ] || NM="$(command -v llvm-nm llvm-nm-18 2>/dev/null | head -1)"
"$NM" -D --undefined-only "$ADDON/test_binary_ps5.so" 2>/dev/null \
  | awk '$1=="U"||$2=="U"{print $NF}' | sort -u > "$ELFDIR/host_exports.list"
sed -i '1i # Generated by tools/ps5-stage2-binary-addon.sh from the test add-on.\n# These are C/C++ runtime symbols the eboot already defines; the generated\n# table (deploy) binds the add-on to the eboot copies. Delete to ship no table.' "$ELFDIR/host_exports.list"
grep -vc '^#' "$ELFDIR/host_exports.list" | xargs -I{} echo "    {} symbols -> $ELFDIR/host_exports.list"

echo "==> staging the add-on into the Kodi build's addons tree"
# Kodi installs add-ons from share/kodi/addons; stage into the build output so
# 30-deploy's share/ copy carries it. (Both the .so and addon.xml.)
DEST="${KODI_BUILD:-$HOME/kodi-ps5-build}/addons/test.binary.ps5"
mkdir -p "$DEST"
cp "$ADDON/addon.xml" "$ADDON/test_binary_ps5.so" "$DEST/"
echo "    staged to $DEST"
echo "==> done. Rebuild+deploy so the export table is linked into the eboot and"
echo "    the add-on ships: scripts/20, cmake --build, scripts/30-deploy.sh"
