#!/usr/bin/env python3
# Generate a C export table from a list of symbol names (one per line): the
# {name, address} pairs the binary-add-on loader's resolver scans to bind an
# add-on's C/C++ runtime imports to the eboot's own copies.
#
# Design constraints learned the hard way from the FSELF converter
# (ps5-native-tool), which segfaults on:
#   - a static array of absolute symbol pointers (.quad symbol): many
#     R_X86_64_RELATIVE relocations in .data -> crash; and
#   - ANY object that adds an __attribute__((constructor)) / .init_array entry
#     -> crash, even with an otherwise-empty table.
# So this file carries NO relocations and NO constructor. It exposes a fill
# function the resolver calls once, lazily, on first lookup; the function body
# assigns &symbol (RIP-relative lea, no static reloc) at run time. The link
# still fails on a missing symbol (its address is taken), keeping the built-in
# "every needed symbol is present" check.
#
# Mangled C++ names are reached via an asm() label on an extern declaration.
import sys

names = [l.strip() for l in sys.stdin if l.strip() and not l.startswith('#')]
names = sorted(set(names))

out = []
out.append('/* generated by ps5-gen-addon-exports.py - do not edit */')
out.append('struct HE { const char* name; void* addr; };')
out.append('')
for i, n in enumerate(names):
    out.append(f'extern char sym_{i}[] __asm__("{n}");')
out.append('')
for i, n in enumerate(names):
    esc = n.replace('\\', '\\\\').replace('"', '\\"')
    out.append(f'static const char name_{i}[] = "{esc}";')
out.append('')
# strong definitions overriding HostExports.cpp's weak defaults. The table is
# zero-initialised (.bss, no relocations); kodi_addon_import_fill() populates it.
out.append(f'struct HE kodi_addon_import_table[{len(names) + 1}];')
out.append(f'unsigned long kodi_addon_import_count = {len(names)};')
out.append('')
# NOT a constructor: called by the resolver on first use (see HostExports.cpp).
out.append('void kodi_addon_import_fill(void)')
out.append('{')
for i in range(len(names)):
    out.append(f'  kodi_addon_import_table[{i}].name = name_{i};')
    out.append(f'  kodi_addon_import_table[{i}].addr = (void*)sym_{i};')
out.append(f'  kodi_addon_import_table[{len(names)}].name = 0;')
out.append(f'  kodi_addon_import_table[{len(names)}].addr = 0;')
out.append('}')
sys.stdout.write('\n'.join(out) + '\n')
